# **ESTATÍSTICA DESCRITIVA**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
df = pd.read_csv('/content/drive/MyDrive/ESTATISTICA-APLICADA/Aula-4/pesquisa_tratada_exemplo.csv',
                      sep=',', encoding='UTF-8')
df.head()

              ra  altura(m) cor_favorita Qual o número de seu calçado?
0  1110482212025       1.85        cinza                            44
1  1110482212030       1.80      laranja                            44
2  1110482212009       1.63     vermelho                            39
3  1110482212036       1.56         azul                            37
4  1110482222039       1.90         azul                            42

In [ ]:
df.shape

(22, 4)

## **Medidas de tendência central**

### Média

In [ ]:
media = df['altura(m)'].mean()
print(media)

1.7109090909090903

In [ ]:
round(df['altura(m)'].mean(),2)

np.float64(1.71)

### Mediana

In [ ]:
df['altura(m)'].median()

1.6949999999999998

### Moda

In [ ]:
df['altura(m)'].mode()

0    1.55
1    1.64
2    1.65
3    1.70
4    1.85
Name: altura(m), dtype: float64

## **Medidas de dispersão**

In [ ]:
df['altura(m)'].var() # Variância amostral

0.014151515151515156

In [ ]:
df['altura(m)'].var(ddof=0) #Variância Populacional

0.013508264462809921

In [ ]:
df['altura(m)'].std() # Desvio padrão amostral

0.11896014102007091

In [ ]:
# sqrt = raiz quadrada
np.sqrt(df['altura(m)'].var(ddof=0)) # Desvio padrão populacional

np.float64(0.11622505953024899)

In [ ]:
df['altura(m)'].mean() # Média

np.float64(1.7109090909090903)

In [ ]:
# Desvio absoluto
(df['altura(m)'] - df['altura(m)'].mean()).abs()

0     0.139091
1     0.089091
2     0.080909
3     0.150909
4     0.189091
5     0.119091
6     0.070909
7     0.169091
8     0.139091
9     0.210909
10    0.029091
11    0.010909
12    0.030909
13    0.070909
14    0.060909
15    0.010909
16    0.129091
17    0.099091
18    0.020909
19    0.060909
20    0.160909
21    0.160909
Name: altura(m), dtype: float64

In [ ]:
# Soma do desvio absoluto
sum((df['altura(m)'] - df['altura(m)'].mean()).abs())

2.203636363636362

In [ ]:
df.describe()

                 ra  altura(m)
count  2.200000e+01  22.000000
mean   1.065053e+12   1.710909
std    2.130800e+11   0.118960
min    1.110482e+11   1.500000
25%    1.110482e+12   1.640000
50%    1.110482e+12   1.695000
75%    1.110482e+12   1.825000
max    1.110482e+12   1.900000

## **Medidas de Posição**

In [ ]:
# Mínimo
df['altura(m)'].min()

1.5

In [ ]:
# Máximo
df['altura(m)'].max()

1.9

In [ ]:
# Primeiro Quartil
df['altura(m)'].quantile(q=0.25)

np.float64(1.64)

In [ ]:
# Segundo Quartil (Mediana)
df['altura(m)'].quantile(q=0.5)

np.float64(1.6949999999999998)

In [ ]:
# Terceiro Quartil
df['altura(m)'].quantile(q=0.75)

np.float64(1.8250000000000002)

In [ ]:
# Percentil 90 (p90)
df['altura(m)'].quantile(q=0.90)

np.float64(1.85)

In [ ]:
df['altura(m)'].describe()

count    22.000000
mean      1.710909
std       0.118960
min       1.500000
25%       1.640000
50%       1.695000
75%       1.825000
max       1.900000
Name: altura(m), dtype: float64

## **Gráfico BoxPlot e Outliers**

### Plotly

In [ ]:
import plotly.express as px

In [ ]:
grafico = px.box(df, y="altura(m)")
grafico.show()